### ISSUE TITLE
Write Documentation.

### ISSUE THREAD

**Issue by dormeneur** [dormeneur/DSA#2]
## Update Readme File.
I will review and label your contribution for Hacktoberfest.

**Comment by negativenagesh** [comment]
@dormeneur 

## Assign it to me

**Comment by dormeneur** [comment]
Alright, I love your readme btw

**Comment by negativenagesh** [comment]
> Alright, I love your readme btw

@dormeneur 

Thank you,

I will update it within tomorrow..

**Comment by dormeneur** [comment]
hi @negativenagesh any updates...

**Comment by negativenagesh** [comment]
@dormeneur Hi,

will finish tomorrow for sure..
