### ISSUE TITLE
Graphs DSA

### ISSUE THREAD

**Issue by dormeneur** [dormeneur/DSA#5]
## Graph Algorithms
1. DFS: Depth-based traversal
2. BFS: Level-based traversal
### Shortest Path:
1. Dijkstra’s Algorithm: Non-negative weighted graphs
2. Bellman-Ford Algorithm: Handles negative weights
3. Floyd-Warshall Algorithm: All-pairs shortest path
### Minimum Spanning Tree (MST):
1. Kruskal’s Algorithm: Uses edges to grow MST
2. Prim’s Algorithm: Uses nodes to grow MST

**Comment by Vibhav-Sharma** [comment]
assign this to me please.
